In [1]:
import pandas as pd
import numpy as np

In [2]:
print ("Hello World")

Hello World

In [3]:
df = pd.DataFrame(data = np.array([[1,2,3], [4,5,6]], dtype=int), columns = ['A', 'B', 'C'])
df

   A  B  C
0  1  2  3
1  4  5  6

In [4]:
data = pd.read_csv('/Users/seanreseigh/Desktop/KSW/combined.csv')

In [5]:
df = pd.DataFrame(data)
df

,Phase,INTID,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Min Green,15,4.0,10.0,0.0,8.0,4.0,10.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Veh Ext,15,3.0,5.0,0.0,4.0,3.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Max Green 1,15,15.0,50.0,0.0,30.0,15.0,50.0,0.0,30.0,0.0,0.0,0.0,15.0,40.0,0.0,0.0,0.0
3,Max Green 2,15,20.0,70.0,0.0,40.0,20.0,70.0,0.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Max Green 3,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,AP Disc,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146,Pmt Green,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
147,Pmt Walk,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148,Pmt Ped Clr,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149,Return Green,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
data = pd.read_csv('https://raw.githubusercontent.com/Seanreseigh1/Test/master/combined.csv')

In [9]:
df = pd.DataFrame(data)
df

,Phase,INTID,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Min Green,15,4.0,10.0,0.0,8.0,4.0,10.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Veh Ext,15,3.0,5.0,0.0,4.0,3.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Max Green 1,15,15.0,50.0,0.0,30.0,15.0,50.0,0.0,30.0,0.0,0.0,0.0,15.0,40.0,0.0,0.0,0.0
3,Max Green 2,15,20.0,70.0,0.0,40.0,20.0,70.0,0.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Max Green 3,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,AP Disc,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146,Pmt Green,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
147,Pmt Walk,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148,Pmt Ped Clr,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149,Return Green,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0